# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9913b7fadcc95587e341e74b38f844a675ea09abfd304cd513aad0cf6bce77cab03aa4c259675a20dcfdd2d2b2d4b2269f6aa9e61bb783189feb062308370910

test:
  secret_key_base: 11f0e582d69a396ae9be8e54cb6208f52c140156f0e338472257eaab203e0c3be19575563d8046a6ca98f2db1f07fff5238bd294c1c1bcfa3b9900ea259be857

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
